FROM node:14.17.0
RUN apt-get install git
RUN git init
RUN git clone https://github.com/jaychaudhari1252/devops-fullstack-app.git
WORKDIR /root/devops-fullstack-app/frontend
EXPOSE 3000
COPY . .
CMD npm install -y  && ["npm" , "start"]